version: "3.3"

services:
  kodski-app:
    container_name: kodski-app
    build: 
      context: .
      dockerfile: ./docker/dev/app.dockerfile
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./app:/app